//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurStore
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int ProductId { get; set; }
        public string SoldBy { get; set; }
        public string Title { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string Condition { get; set; }
        public decimal Price { get; set; }
        public bool PriceNegotiable { get; set; }
        public string UsedFor { get; set; }
        public string Warrenty { get; set; }
        public string Discount { get; set; }
        public bool IsHide { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
    }
}
