//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostAd
    {
        public PostAd()
        {
            this.Comments = new HashSet<Comment>();
            this.FeatureAds = new HashSet<FeatureAd>();
            this.Spams = new HashSet<Spam>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string Condition { get; set; }
        public decimal Price { get; set; }
        public bool PriceNegotiable { get; set; }
        public string UsedFor { get; set; }
        public string Warrenty { get; set; }
        public bool IsHide { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public bool IsFeatured { get; set; }
        public string Status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<FeatureAd> FeatureAds { get; set; }
        public virtual Product Product { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<Spam> Spams { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
