//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Comments = new HashSet<Comment>();
            this.Contacts = new HashSet<Contact>();
            this.FeatureAds = new HashSet<FeatureAd>();
            this.PostAds = new HashSet<PostAd>();
            this.Spams = new HashSet<Spam>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string Zone { get; set; }
        public string City { get; set; }
        public string LocalAddress { get; set; }
        public string FirstPhone { get; set; }
        public string SecondPhone { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string UserRole { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<FeatureAd> FeatureAds { get; set; }
        public virtual ICollection<PostAd> PostAds { get; set; }
        public virtual ICollection<Spam> Spams { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
